#pragma once

#define CORE1 0
#define CORE2 1

#define TASK_CORE_CAN CORE2
#define TASK_CORE_KLINE_PROTOCOL CORE2
#define TASK_CORE_LEAF_PROTOCOL CORE2

#define TASK_PRIORITY_CAN_STATUS 7
#define TASK_PRIORITY_CAN_RX 8
#define TASK_PRIORITY_KLINE_PROTOCOL 7
#define TASK_PRIORITY_LEAF_PROTOCOL 7
#define TASK_PRIORITY_CAN_CONTROL 10
#define TASK_PRIORITY_DEBUG 20
